# Generated by Django 4.2.4 on 2023-09-18 11:13

import addresses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='global_plus_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Global Plus Code'),
        ),
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=addresses.models.CompressedTextField(blank=True, max_length=250, verbose_name='Place ID'),
        ),
    ]
