[tool.poetry]
name = "weather-zone"
version = "0.1.0"
description = ""
authors = ["Ian Buttimer <ibuttimer@yahoo.com>"]
readme = "README.md"
packages = [{include = "weather_zone"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
